{% set name = "prefixmaps" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prefixmaps-{{ version }}.tar.gz
  sha256: 7421e1244eea610217fa1ba96c9aebd64e8162a930dc0626207cd8bf62ecf4b9

build:
  entry_points:
    - slurp-prefixmaps = prefixmaps.ingest.etl_runner:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pyyaml >=5.3.1
    - curies >=0.5.3

test:
  imports:
    - prefixmaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A python library for retrieving semantic prefix maps
  license: Apache-2.0
  license_file: LICENSE
  home: https://linkml.io/prefixmaps/

extra:
  recipe-maintainers:
    - dstansby
