{% set name = "prefixmaps" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prefixmaps-{{ version }}.tar.gz
  sha256: ae86a1b31189d0516d199756d5808f75f44b39e86546c356cc78c0fe8d2078af

build:
  entry_points:
    - slurp-prefixmaps = prefixmaps.ingest.etl_runner:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pyyaml >=5.3.1
    - curies >=0.5.3

test:
  imports:
    - prefixmaps
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A python library for retrieving semantic prefix maps
  license: Apache-2.0
  license_file: LICENSE
  home: https://linkml.io/prefixmaps/

extra:
  recipe-maintainers:
    - dstansby
